/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_imsUA (void);
GtkWidget* create_help (void);
GtkWidget* create_preferences (void);
GtkWidget* create_im_window (void);
GtkWidget* create_xdms_download_window (void);
GtkWidget* create_xdms_upload_window (void);
GtkWidget* create_xml_file_dialog (void);
GtkWidget* create_aboutdialog (void);
GtkWidget* create_vod_window (void);
GtkWidget* create_iptv_vod_epg_window (void);
GtkWidget* create_iptv_epg_window (void);
